### PR TITLE
UPDATE refactorized

### PR DESCRIPTION
**Pull request by debdutgoswami**
**REFACTORED**

I have refactored the ipynb file into separate files. To execute the  code, run the main.py file. The paths to the inputs might be altered depending on the directory cloned to. Hope this resolves the issue. Thank You,

**Regards,
Debdut Goswami**

### CODE REVIEW

**Comment by ucalyptus** [comment]
Thank you @debdutgoswami . Looks good. One thing. Just keep the ipynb separately intact in your branch since ipynb can be viewed using nbviewer so that can be used as a link

**Comment by ucalyptus** [comment]
I will merge this PR after that. 
However you can check your status at https://hacktoberfest.digitalocean.com/profile

**Comment by ucalyptus** [comment]
I see you already have the ipynb separately intact. Thanks!
Merging it .

**Comment by debdutgoswami** [comment]
Glad I could be of help.

**Pull request merged**
